[WIP] Implement getItemURL for Dropbox
remotestorage/remotestorage.js pull request #1130
Opened 2018-06-02 16:36 UTC by Ragnis

#1052

2018-11-17 12:32 UTC, skddc commented
@Ragnis Is this actually still work in progress? Looks to me like this is basically done.

2019-02-14 08:51 UTC, skddc commented
@Ragnis Would be cool if you could update us on the status here. See my question from November.

2019-02-14 11:31 UTC, Ragnis commented
I guess it is done. I re-based the code to latest master and also fixed the tests.

2019-02-19 08:39 UTC, raucao requested changes
I just played around with this branch in Sharesome and found a logical bug with the implementation:

The way the function works on a normal BaseClient is that the path argument is relative to the client scope. So when used in a module, the `publicClient` would have a base of `mymodulename/public/`. Hence the `makePath()` call here: https://github.com/remotestorage/remotestorage.js/blob/master/src/baseclient.js#L299

However, this implementation doesn't add the base path, and so `_itemRefs` aren't matched correctly when calling `getItemURL()` with a relative path (in the shares module that would just be a filename e.g.). This results in `undefined` being returned instead of the stored public URL from `_itemRefs`.

---

Another thing, but I'm not 100% sure how to solve it, is that `storeFile()` actually returns a URL on a normal BaseClient, but we only overwrite `put` in the Dropbox class, and returning a simple URL from that broke it for me when I tried to add it.

2026-05-31 11:21 UTC, raucao commented
Closing in favor of #1389

2026-05-31 11:21 UTC, closed without merging